# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q92gY2EA2fnmy5dhbyUNXzv8YYJHut7m
"""

from fastapi import FastAPI
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import jdatetime
from datetime import datetime
import json
import os


app = FastAPI()

@app.post("/run")
def run_task():

    # ----------------------------
    # 1) احراز هویت
    # ----------------------------
    scope = [
        "https://spreadsheets.google.com/feeds",
        "https://www.googleapis.com/auth/drive"
    ]
    print(">>>> ENV LENGTH:", len(os.environ.get("GOOGLE_CREDS_JSON", "")))

    creds_json_str = os.environ.get("GOOGLE_CREDS_JSON")
    creds_dict = json.loads(creds_json_str)
    creds = ServiceAccountCredentials.from_json_keyfile_dict(creds_dict, scope)
    client = gspread.authorize(creds)


    # ----------------------------
    # 2) باز کردن شیت‌ها
    # ----------------------------
    sheet_file = client.open("unload_data")
    raw_sheet = sheet_file.worksheet("raw_data")
    final_sheet = sheet_file.worksheet("final_data")

    # ورودی‌ها (از شیت final_data)
    input_data = final_sheet.get_values('A1:C1')

    # ----------------------------
    # 3) خواندن raw_data → DataFrame
    # ----------------------------
    raw_data = raw_sheet.get_all_values()
    df = pd.DataFrame(raw_data[1:], columns=raw_data[0])

    # ----------------------------
    # 4) تبدیل تاریخ شمسی → میلادی
    # ----------------------------
    def jalali_to_gregorian(jalali_str):
        try:
            parts = jalali_str.replace('-', '/').split('/')
            y, m, d = map(int, parts)
            g_date = jdatetime.date(y, m, d).togregorian()
            return g_date.strftime("%Y-%m-%d")
        except:
            return None

    df["gregorian_date"] = df.iloc[:, 0].apply(jalali_to_gregorian)

    # ----------------------------
    # 5) فیلتر تاریخ
    # ----------------------------
    start_date = pd.to_datetime(input_data[0][0])
    end_date = pd.to_datetime(input_data[0][1])

    df["gregorian_date"] = pd.to_datetime(df["gregorian_date"])
    df_filtered = df[(df["gregorian_date"] >= start_date) &
                     (df["gregorian_date"] <= end_date)]

    # ----------------------------
    # 6) تبدیل ستون‌های عددی
    # ----------------------------
    cols_to_sum = df_filtered.columns[2:-1]
    df_filtered[cols_to_sum] = (
        df_filtered[cols_to_sum]
        .apply(pd.to_numeric, errors="coerce")
        .fillna(0)
    )

    # ----------------------------
    # 7) گروه‌بندی داده‌ها
    # ----------------------------
    group_col = df_filtered.columns[1]
    grouped_sum = (
        df_filtered.groupby(group_col)[cols_to_sum].sum().reset_index()
    )

    df = grouped_sum.copy()

    # ----------------------------
    # 8) درصد هر ستون = مقدار سطر / جمع ستون
    # ----------------------------
    cols = df.columns.drop("hour")

    col_sum = df[cols].sum()

    for c in cols:
        pct_col = f"درصد_{c}"
        idx = df.columns.get_loc(c)
        df.insert(idx + 1, pct_col, (df[c] / col_sum[c] * 100).round(1))

    # ----------------------------
    # 9) پاک کردن فقط ستون F به بعد
    # ----------------------------
    final_data = sheet_file.worksheet("final_data")

    num_rows = len(final_data.get_all_values())
    num_cols = len(final_data.row_values(1))

    if num_cols >= 6:
        end_col = gspread.utils.rowcol_to_a1(1, num_cols).replace("1", "")
        final_data.batch_clear([f"F1:{end_col}{num_rows}"])

    # ----------------------------
    # 🔟 نوشتن خروجی از F1
    # ----------------------------
    data = [df.columns.tolist()] + df.values.tolist()
    final_data.update("F1", data)

    return {"status": "ok", "rows_written": len(data)}
